const ResponseCode = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  UNPROCESSABLE_REQUEST: 422,
  INTERNAL_SERVER_ERROR: 500,
  TOKEN_INVALID: 503,
  NO_INTERNET: 522,
  BAD_GATEWAY: 502,
  REQUEST_TIMEOUT: 408,
  PAYMENT_REQUIRED: 402
};

const APIURL = {
  local: '',
  dev: '',
  qa: '',
  production: '',
}


export {
  ResponseCode,
  APIURL
}
